backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets/blog" 
public_folder: "/assets/blog" 
collections:
  - name: "GameInfo"
    label: "GameInfo"
    folder: "src/gameInfo"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "ImageAlt", name: "imageAlt", widget: "string"}
      - {label: "id", name: "id", widget: "integer"}
      - {label: "Description", name: "description", widget: "string"}